global_frame: /map
rolling_window: true
width: 1.0
height: 1.0
plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
