nxt_robot:
      - type: motor
        name: base_to_rwheel
        port: PORT_A
        desired_frequency: 20.0
      - type: motor
        name: base_to_leftwheel
        port: PORT_C
        desired_frequency: 20.0
