// Generated by gencpp from file nxt_msgs/Light.msg
// DO NOT EDIT!


#ifndef NXT_MSGS_MESSAGE_LIGHT_H
#define NXT_MSGS_MESSAGE_LIGHT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace nxt_msgs
{
template <class ContainerAllocator>
struct Light_
{
  typedef Light_<ContainerAllocator> Type;

  Light_()
    : header()
    , intensity(0.0)  {
    }
  Light_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , intensity(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _intensity_type;
  _intensity_type intensity;





  typedef boost::shared_ptr< ::nxt_msgs::Light_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nxt_msgs::Light_<ContainerAllocator> const> ConstPtr;

}; // struct Light_

typedef ::nxt_msgs::Light_<std::allocator<void> > Light;

typedef boost::shared_ptr< ::nxt_msgs::Light > LightPtr;
typedef boost::shared_ptr< ::nxt_msgs::Light const> LightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nxt_msgs::Light_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nxt_msgs::Light_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nxt_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'nxt_msgs': ['/home/user/catkin_testws/src/test1/src/nxt/nxt_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nxt_msgs::Light_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nxt_msgs::Light_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nxt_msgs::Light_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nxt_msgs::Light_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nxt_msgs::Light_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nxt_msgs::Light_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nxt_msgs::Light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ff9119148a4a3f3a31d0a976a2a2cd04";
  }

  static const char* value(const ::nxt_msgs::Light_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xff9119148a4a3f3aULL;
  static const uint64_t static_value2 = 0x31d0a976a2a2cd04ULL;
};

template<class ContainerAllocator>
struct DataType< ::nxt_msgs::Light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nxt_msgs/Light";
  }

  static const char* value(const ::nxt_msgs::Light_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nxt_msgs::Light_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 intensity\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::nxt_msgs::Light_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nxt_msgs::Light_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.intensity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Light_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nxt_msgs::Light_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nxt_msgs::Light_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "intensity: ";
    Printer<double>::stream(s, indent + "  ", v.intensity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NXT_MSGS_MESSAGE_LIGHT_H
