// Generated by gencpp from file nxt_msgs/Range.msg
// DO NOT EDIT!


#ifndef NXT_MSGS_MESSAGE_RANGE_H
#define NXT_MSGS_MESSAGE_RANGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace nxt_msgs
{
template <class ContainerAllocator>
struct Range_
{
  typedef Range_<ContainerAllocator> Type;

  Range_()
    : header()
    , range(0.0)
    , range_min(0.0)
    , range_max(0.0)
    , spread_angle(0.0)  {
    }
  Range_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , range(0.0)
    , range_min(0.0)
    , range_max(0.0)
    , spread_angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _range_type;
  _range_type range;

   typedef double _range_min_type;
  _range_min_type range_min;

   typedef double _range_max_type;
  _range_max_type range_max;

   typedef double _spread_angle_type;
  _spread_angle_type spread_angle;





  typedef boost::shared_ptr< ::nxt_msgs::Range_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nxt_msgs::Range_<ContainerAllocator> const> ConstPtr;

}; // struct Range_

typedef ::nxt_msgs::Range_<std::allocator<void> > Range;

typedef boost::shared_ptr< ::nxt_msgs::Range > RangePtr;
typedef boost::shared_ptr< ::nxt_msgs::Range const> RangeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nxt_msgs::Range_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nxt_msgs::Range_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nxt_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'nxt_msgs': ['/home/user/catkin_testws/src/test1/src/nxt/nxt_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nxt_msgs::Range_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nxt_msgs::Range_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nxt_msgs::Range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nxt_msgs::Range_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nxt_msgs::Range_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nxt_msgs::Range_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nxt_msgs::Range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37a3243712d0ae8a8c4863ac843a1c75";
  }

  static const char* value(const ::nxt_msgs::Range_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37a3243712d0ae8aULL;
  static const uint64_t static_value2 = 0x8c4863ac843a1c75ULL;
};

template<class ContainerAllocator>
struct DataType< ::nxt_msgs::Range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nxt_msgs/Range";
  }

  static const char* value(const ::nxt_msgs::Range_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nxt_msgs::Range_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64 range\n\
float64 range_min\n\
float64 range_max\n\
float64 spread_angle\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::nxt_msgs::Range_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nxt_msgs::Range_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.range);
      stream.next(m.range_min);
      stream.next(m.range_max);
      stream.next(m.spread_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Range_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nxt_msgs::Range_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nxt_msgs::Range_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "range: ";
    Printer<double>::stream(s, indent + "  ", v.range);
    s << indent << "range_min: ";
    Printer<double>::stream(s, indent + "  ", v.range_min);
    s << indent << "range_max: ";
    Printer<double>::stream(s, indent + "  ", v.range_max);
    s << indent << "spread_angle: ";
    Printer<double>::stream(s, indent + "  ", v.spread_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NXT_MSGS_MESSAGE_RANGE_H
